### ISSUE TITLE
bamboo.profile.txt missing

### ISSUE THREAD

**Issue by cpbridges** [DependableSystemsLab/LLFI-GPU#1]
Hi Folks,
I'm looking to test this library and have all the dependancies installed. The python script profile.py however does not generate a bamboo.profile.txt file and so cannot continue.
Which process is generating this file?
Best, Chris

**Comment by cclinus** [comment]
Which CUDA version are you running ? Are there any other errors reported ? Did you successfuly do the fault injection in the example benchmark ? Please give more context here.

**Comment by cpbridges** [comment]
Thanks for the fast response cclinus. 

We're running CUDA 8.0.33. The errors we got are in the shots below, and we wanted to try with the example code first - so all on the example.cu (which nvcc compiles fine). Our outputs are below:

```
cpb@cpb-VirtualBox:~/Documents/LLFI-GPU-master$ python profile.py
mkdir: cannot create directory ‘bamboo_fi’: File exists
mkdir: cannot create directory ‘bamboo_fi/baseline’: File exists
***[GPGPU-BAMBOO]*** Generating Profiling Pass ...
example.cu(148): warning: conversion from a string literal to "char *" is deprecated

example.cu(149): warning: conversion from a string literal to "char *" is deprecated

example.cu(148): warning: conversion from a string literal to "char *" is deprecated

example.cu(149): warning: conversion from a string literal to "char *" is deprecated

***[GPGPU-BAMBOO]*** Generating Profiling Traces ...
rm: cannot remove ‘bamboo.profile.txt’: No such file or directory
.
.
.
mv: cannot stat ‘bamboo.profile.txt’: No such file or directory
mv: cannot stat ‘opt_bamboo_before.ll’: No such file or directory
mv: cannot stat ‘opt_bamboo_after.ll’: No such file or directory
***[GPGPU-BAMBOO]*** Done!
```

**Comment by cclinus** [comment]
We only tested LLFI-GPU on CUDA-6. You can download and install CUDA-6 and try again. It is allowed to have multiple CUDA versions without uninstalling each other. 

If you can extend LLFI-GPU to CUDA-8, welcome to send us a patch too.

**Comment by cpbridges** [comment]
OK, We'll try that. 

In the meantime, can you point to the command/line in the python where the bamboo.profile.txt is generated? (I can't see why moving from 8 to 6 will affect this issue in a missing file - happy to be proven wrong however!).

**Comment by cclinus** [comment]
See in this file (line 31): 
bamboo_lib/profiling_lib/bamboo_profiling.cu

profile.py takes your benchmark and link with this file which generates the bamboo.profile.txt . It should be your CUDA version problem. Try 6 and let me know if you still encounter problems.

Thanks

Justin

**Comment by bbabatunde** [comment]
I am getting the same error as cpbridges  and I  have all the dependencies listed.

This is what I get when I run python profile.py

baba@rousseau:~/LLFI-GPU$ python profile.py 
***[GPGPU-BAMBOO]*** Generating Profiling Pass ... 
Profiling pass installed ... 
***[GPGPU-BAMBOO]*** Generating Profiling Traces ... 
rm: cannot remove `bamboo.profile.txt': No such file or directory
Time spent by GPU: 0.031232 ms.
Time spent by CPU: 0.026976 ms.
Matrices are not the same
Matrices are not the same
Matrices are not the same
Matrices are not the same
Matrices are not the same
Matrices are not the same


Here is my system information:

baba@rousseau:~$ python --version
Python 2.7.12

baba@rousseau:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Thu_Mar_13_11:58:58_PDT_2014
Cuda compilation tools, release 6.0, V6.0.1

baba@rousseau:~$ clang --version
Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

baba@rousseau:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"

**Comment by bbabatunde** [comment]
I discovered that when I run libnvcc.so I get a segmentation fault

baba@rousseau:~/LLFI-GPU/bamboo_lib/profiling_lib$ ./libnvcc.so nvcc ../../example.cu -o example.o
Segmentation fault (core dumped)

**Comment by cclinus** [comment]
Hi bbabatunde,

The output from your "python profile.py" is correct, when "bamboo.profile.txt" is not there for the first time, the command "rm 'bamboo.profile.txt' " will generate "rm: cannot remove `bamboo.profile.txt': No such file or directory". This is because profile.py need make sure there is no previous existing bamboo.profile.txt in the same folder.

So based on what you showed in your profile.py output, you have successfully instrument the GPU code for profiling. You can verify this by checking if "\bamboo_fi\example_profile.ll" is generated! If so, all you need to do is to run "python inject.py" to do the actual fault injections ! Can you do it and tell me if you succeed ? 

BTW, the way you manually load libnvcc.so is not correct, you should try "CICC_MODIFY_OPT_MODULE=1 LD_PRELOAD=./libnvcc.so nvcc -arch=sm_30 -rdc=true -dc -g -G -Xptxas -O0 -D BAMBOO_PROFILING  example.cu -o example.o   -D KERNELTRACE" in your LLFI-GPU root folder after copying everything from "bamboo_lib/profiling/*" to the root folder, if you want to step into each process. These commands are well iterated in the "profile.py" script.

A tip is that it is safe you remove "bamboo_fi " folder every time you want to redo your fault injections, because this folder contains the fault injection results from your previous fault injection rounds.
