### ISSUE TITLE
bamboo.profile.txt missing

### ISSUE THREAD

**Issue by bbabatunde** [DependableSystemsLab/LLFI-GPU#2]
I am getting the same error as cpbridges and I have all the dependencies listed.

This is what I get when I run python profile.py

baba@rousseau:~/LLFI-GPU$ python profile.py
[GPGPU-BAMBOO] Generating Profiling Pass ...
Profiling pass installed ...
[GPGPU-BAMBOO] Generating Profiling Traces ...
rm: cannot remove `bamboo.profile.txt': No such file or directory
Time spent by GPU: 0.031232 ms.
Time spent by CPU: 0.026976 ms.
Matrices are not the same
Matrices are not the same
Matrices are not the same
Matrices are not the same
Matrices are not the same
Matrices are not the same

Here is my system information:

baba@rousseau:~$ python --version
Python 2.7.12

baba@rousseau:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Thu_Mar_13_11:58:58_PDT_2014
Cuda compilation tools, release 6.0, V6.0.1

baba@rousseau:~$ clang --version
Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

baba@rousseau:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"

**Comment by bbabatunde** [comment]
I discovered that when I run libnvcc.so I get a segmentation fault

baba@rousseau:~/LLFI-GPU/bamboo_lib/profiling_lib$ ./libnvcc.so nvcc ../../example.cu -o example.o
Segmentation fault (core dumped)

**Comment by cclinus** [comment]
Hi bbabatunde,

The output from your "python profile.py" is correct, when "bamboo.profile.txt" is not there for the first time, the command "rm 'bamboo.profile.txt' " will generate "rm: cannot remove `bamboo.profile.txt': No such file or directory". This is because profile.py need make sure there is no previous existing bamboo.profile.txt in the same folder.

So based on what you showed in your profile.py output, you have successfully instrument the GPU code for profiling. You can verify this by checking if "\bamboo_fi\example_profile.ll" is generated! If so, all you need to do is to run "python inject.py" to do the actual fault injections ! Can you do it and tell me if you succeed ?

BTW, the way you manually load libnvcc.so is not correct, you should try "CICC_MODIFY_OPT_MODULE=1 LD_PRELOAD=./libnvcc.so nvcc -arch=sm_30 -rdc=true -dc -g -G -Xptxas -O0 -D BAMBOO_PROFILING example.cu -o example.o -D KERNELTRACE" in your LLFI-GPU root folder after copying everything from "bamboo_lib/profiling/*" to the root folder, if you want to step into each process. These commands are well iterated in the "profile.py" script.

A tip is that it is safe you remove "bamboo_fi " folder every time you want to redo your fault injections, because this folder contains the fault injection results from your previous fault injection rounds.

**Comment by bbabatunde** [comment]
Okay, I will do that.

However, I am still confused about why the value in the matrix do not match the  GPU values.The results.txt only had zeros in them which is different from the CPU values

**Comment by bbabatunde** [comment]
Here is my python inject.py

baba@rousseau:~/LLFI-GPU$ python inject.py 
***[GPGPU-BAMBOO]*** Generating Injection Pass ... 
Traceback (most recent call last):
  File "inject.py", line 270, in <module>
    main()
  File "inject.py", line 264, in main
    groupProfileLines()
  File "inject.py", line 61, in groupProfileLines
    with open("bamboo_fi/bamboo.profile.txt", "r") as ins:
IOError: [Errno 2] No such file or directory: 'bamboo_fi/bamboo.profile.txt'

**Comment by cclinus** [comment]
Do two things:
1. Compile and run example.cu using your nvcc, and see the result.txt, make sure you can execute the example code no problem. I.e, "nvcc -arch=sm_30 -rdc=true -O0 example.cu -o example.exe"
2. After profile.py, take a look at "bamboo_fi\example_profile.ll", see whether the instrumentation is correct.

Did you run inject.py right after your profile.py ? They have to be in order. After profile.py, you should see "bamboo_fi/bamboo.profile.txt" and hence inject.py should find it. 

3. So confirm bamboo_fi/bamboo.profile.txt is there after profile.py, if there, take a look at whats in the file.

**Comment by bbabatunde** [comment]
what does this part  "-arch=sm_30 -rdc=true"  of the command in 1 do.
So when I run "nvcc -arch=sm_30 -rdc=true -O0 example.cu -o example.exe" ,I get the same "matrices are not the same" error but when I run "nvcc example.cu -o example.exe" everything works fine and the result are the same with the CPU values.


baba@rousseau:~/LLFI-GPU$ nvcc example.cu -o example.exe
nvcc warning : The 'compute_10' and 'sm_10' architectures are deprecated, and may be removed in a future release.

I do have a bamboo_fi\example_profile.ll and I run the commands in order

**Comment by bbabatunde** [comment]
**without -arch=sm_30 -rdc=true**

baba@rousseau:~/LLFI-GPU$ nvcc example.cu -o example.exe
nvcc warning : The 'compute_10' and 'sm_10' architectures are deprecated, and may be removed in a future release.
baba@rousseau:~/LLFI-GPU$ ./example.exe 
Time spent by GPU: 0.059712 ms.
Time spent by CPU: 0.027328 ms.

**Comment by bbabatunde** [comment]
without "-arch=sm_30 -rdc=true"
baba@rousseau:~/LLFI-GPU$ nvcc example.cu -o example.exe
nvcc warning : The 'compute_10' and 'sm_10' architectures are deprecated, and may be removed in a future release.
baba@rousseau:~/LLFI-GPU$ ./example.exe 
Time spent by GPU: 0.059712 ms.
Time spent by CPU: 0.027328 ms.

**Comment by cclinus** [comment]
Then I think the problem is quite clear. sm_30 compiles to Kepler code which is the default compilation in LLFI-GPU. I guess you used an old GPU. You should change sm_30 to the one that your hardware supports, say sm_20 for Fermi etc. Change these in profile.py and inject.py, and see if it works. I have not tested on other GPUs except Kepler ones. I used K20 and GTX960, which support sm_30.

Test it, and let us know. Thanks.

**Comment by bbabatunde** [comment]
Yeah, turns out the hardware is tesla based and supports sm_10 which do not support rdc.

Thanks for your help, really appreciate.

**Comment by cclinus** [comment]
If you can change the compilation parameters for Tesla and get it to work. Let us know.

**Comment by bbabatunde** [comment]
Got a Fermi GPU and everything works fine now.

just had to change "nvcc -arch=sm_30 -rdc=true -O0 example.cu -o example.exe" to "nvcc -arch=sm_20 -rdc=true -O0 example.cu -o example.exe"
